### PR TITLE
Support rsyncing files into place

### PR DESCRIPTION
**Pull request by rahulsom**
This would solve these use cases

* `.groovy/grapeConfig`
* `.config/nvim/init.vim`
* `.config/fish/conf.d/*.fish`

### CODE REVIEW

**Comment by rahulsom** [comment]
@DanielThomas Does this PR make sense to merge?

**Comment by DanielThomas** [comment]
I try to keep the files within the dotfiles sources authoritative and unable to skew (i.e. not require an install/update if you change them). I bet I can come up with something that'll allow these to be symlinked, let me think about it.

**Comment by DanielThomas** [comment]
`.symlink` can now be directories, and it'll symlink those files relatively in that directory:

```
  [ .. ] linking /Users/dannyt/.dotfiles/config.symlink/nvim/init.vim to /Users/dannyt/.config/nvim/init.vim
  [ OK ] linked /Users/dannyt/.dotfiles/config.symlink/nvim/init.vim to /Users/dannyt/.config/nvim/init.vim
  [ .. ] linking /Users/dannyt/.dotfiles/config.symlink/fish/conf.d/test to /Users/dannyt/.config/fish/conf.d/test
  [ OK ] linked /Users/dannyt/.dotfiles/config.symlink/fish/conf.d/test to /Users/dannyt/.config/fish/conf.d/test
  [ .. ] linking /Users/dannyt/.dotfiles/config.symlink/fish/conf.d/test2 to /Users/dannyt/.config/fish/conf.d/test2
  [ OK ] linked /Users/dannyt/.dotfiles/config.symlink/fish/conf.d/test2 to /Users/dannyt/.config/fish/conf.d/test2
```

See if that works for you instead.

**Comment by rahulsom** [comment]
Thanks! That seems like a cleaner solution. And it works as expected.

**Pull request closed without merging**
