### PR TITLE
Support composing `.gitconfig`

### PR DESCRIPTION
**Pull request by rahulsom**

### CODE REVIEW

**Comment by rahulsom** [comment]
@DanielThomas Does this PR make sense to merge?

**Comment by DanielThomas** [comment]
You can do this just fine with a symlink file for your main `.gitconfig` and `include`:

I do this:
```
https://github.com/DanielThomas/dotfiles/blob/master/git/gitconfig.symlink#L1-L2
```

Which then composes in my other configs:
```
[include]
    path = /Users/dannyt/.gitconfig_metatron
    path = /Users/dannyt/.gitconfig_user
```

So I end up with:
```
lrwxr-xr-x   1 dannyt staff    52 Jun 24 12:21  .gitconfig -> /Users/dannyt/.dotfiles_public/git/gitconfig.symlink
lrwxr-xr-x   1 dannyt staff    47 Dec 10  2020  .gitconfig_local -> /Users/dannyt/.dotfiles/gitconfig_local.symlink
lrwxr-xr-x   1 dannyt staff    50 Dec 10  2020  .gitconfig_metatron -> /Users/dannyt/.dotfiles/gitconfig_metatron.symlink
lrwxr-xr-x   1 dannyt staff    46 Dec 10  2020  .gitconfig_user -> /Users/dannyt/.dotfiles/gitconfig_user.symlink
lrwxr-xr-x   1 dannyt staff    59 Dec 10  2020  .gitignore_global -> /Users/dannyt/.dotfiles_public/git/gitignore_global.symlink
```

**Comment by rahulsom** [comment]
The problem with gitconfig is it doesn't allow relative paths or substitution of `$HOME` and `~`.
Your example has `/Users/dannyt` hardcoded in it. 
That makes it hard to share dotfiles with other users.

The other problem is composing `.gitconfig_local`. I think there should be some installation step that composes it automatically.

**Comment by DanielThomas** [comment]
Expansion of `~` was added in Git 1.7.10.2 and paths may be relative:

https://stackoverflow.com/a/9733277/364206

**Comment by rahulsom** [comment]
Got it. I've hacked around it to use an `install.sh` to get it going. Thanks!

**Comment by DanielThomas** [comment]
Can recommend the `gitconfig.symlink` to bootstrap all of the includes. I updated all of mine to be relative now that's supported and it works nicely. I only had to continue to use `~` for ssl cert paths.

**Pull request closed without merging**
